# version: '3.8'
# services:
#   nest-api:
#     container_name: nest-api
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 3001:3001
#     depends_on:
#       - postgres
#     env_file:
#       - .env

#   postgres:
#     image: postgres:13
#     container_name: postgres
#     restart: always
#     ports:
#       - 5432:5432
#     env_file:
#       - .env
#     volumes:
#       - postgres:/var/lib/postgresql/data

# volumes:
#   postgres:
#     name: nest-db

version: '3.8'

services:
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            dockerfile: Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: nestjs_api_prod
        image: nestjs-api-prod:1.0.0
        build:
            context: .
            dockerfile: Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    nesjs-network: